#### Local vs Global Variable

In [2]:
# what will be the output?
def fun():
    a = []
    for i in range(5): # i = 0, 1, 2, 3, 4
        a.append(i)
    return a

b = fun()
print(b)

[0, 1, 2, 3, 4]


In [4]:
a = [] # outside of the function, it becomes a global variable

def fun():
    
    for i in range(5): # i = 0, 1, 2, 3, 4
        a.append(i)
    return a

fun()
print(a)

[0, 1, 2, 3, 4]


In [5]:
def add(x, y):
    total = 0
    total = x + y
    return total
add(3, 4)

7

In [7]:
def add(x, y, z):
    total = 0
    total = x + y + z
    return total
add(3, 4, 5)

12

In [10]:
# when the number of arguments is unknown
def add(*values):
    total = 0
    for i in values:
        total = total + i
    return total

In [13]:
add(1,2,7,9)

19

In [14]:
# unknown number of key-value pairs or default arguments
def stdRecord(**args):
    print(args)

In [15]:
stdRecord(name = 'Adam', id = '1235', grade = 3.9)

{'name': 'Adam', 'id': '1235', 'grade': 3.9}


### Lambda function
- used for short function definition
- an anonymous function without a name and the 'def' keyword
- lambda function allows us to use a function as a parameter of another function
- basic syntax: 3 parts of a lambda function -> 1. lambda keyword 2. parameters 3. body

In [16]:
def add(x,y):
    return (x+y)
add(4,5)

9

In [17]:
# lambda function
add = lambda x,y: x+y
add(4,5)

9

In [18]:
# find the area of a circle. area = pi * r * r
area = lambda r, PI: PI * r * r 
area(5, 3.14)

78.5

In [19]:
# find the area of a circle. area = pi * r * r
area = lambda r, PI = 3.14: PI * r * r 
area(5)

78.5

In [20]:
# create a list of numbers from 1 to 10. After creating the list, we will square all the list items.
listOfNumbers = list(range(1,11))
listOfNumbers

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [21]:
def makeSquare(aList):
    updatedNumbers = []
    for item in aList:
        newItem = item * item
        updatedNumbers.append(newItem)
    return updatedNumbers

makeSquare(listOfNumbers)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

### map function
- is used to apply a particular operation to every element in a sequence (e.g., list)
- syntax: map(function, sequence)

In [24]:
updatedList = map(lambda x: x*x, listOfNumbers)
list(updatedList)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

## NumPy
- Stands for Numerical Python
- Efficient to implement the concepts of arrays, metrices
- Faster and takes less memory compated to a list
- Fast in performing arithmetic operations and also for broadcasting
- one of the main building blocks for several machine learning libraries

In [26]:
import numpy as np

In [27]:
# numpy array can be created as
tup = (1,2,3)
arr = np.array(tup)
arr

array([1, 2, 3])

In [28]:
type(arr)

numpy.ndarray

In [29]:
aList = [1,2,3]
arr = np.array(aList)
arr

array([1, 2, 3])

In [30]:
# 2D numpy array
bList = [[1,2,3], [4,5,6]]
bArr = np.array(bList)
bArr

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# In list, we use range() to create a sequence of numbers
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [32]:
# arange()
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
np.full((3,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
# specific number of linearly spaced elements
np.linspace(0, 1, 50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [40]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [41]:
# random numbers using numpy
np.random.rand(10)

array([0.72854637, 0.08544919, 0.24009924, 0.23361036, 0.00878742,
       0.31928164, 0.59804483, 0.95771957, 0.44833377, 0.946396  ])

In [42]:
# 2D array
np.random.rand(4,5)

array([[0.67594922, 0.39264456, 0.86171785, 0.12245134, 0.64017684],
       [0.63090287, 0.79200509, 0.97654742, 0.30067349, 0.34812631],
       [0.39796348, 0.42695898, 0.54655426, 0.79291441, 0.45058072],
       [0.13186547, 0.79472288, 0.76349568, 0.82068841, 0.74940176]])

In [52]:
# one randomly generated integer
np.random.randint(1,100)

34

In [53]:
# a series of random integer. 
# syntax: start, end, how_many where 'end' is not inclusive
np.random.randint(1,101,10)

array([24, 73, 76, 15, 58, 43, 50, 45, 74, 37])

In [57]:
# 2D array from 1D array
np.arange(25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Accessing elements from a numPy array

In [58]:
arr = np.random.randint(1, 50, 10)
arr

array([ 2, 41,  2, 32, 48, 48, 32,  4,  2,  9])

In [59]:
arr[0]

2

In [60]:
arr[9]

9

In [61]:
arr[-1]

9

In [62]:
arr[-2]

2

In [63]:
arr

array([ 2, 41,  2, 32, 48, 48, 32,  4,  2,  9])

In [64]:
arr[1:4]

array([41,  2, 32])

In [66]:
arr[3:]

array([32, 48, 48, 32,  4,  2,  9])

In [72]:
# start:end:step
arr[2:6:2]

array([ 2, 48])

In [73]:
arr = np.random.randint(1, 51, (3,4))
arr

array([[31, 50, 39,  8],
       [32, 46, 24, 41],
       [44, 14, 43,  4]])

In [74]:
arr[0][0]

31

In [75]:
arr[0 , 0]

31

In [77]:
arr[0]

array([31, 50, 39,  8])

In [78]:
arr[0][1:3]

array([31, 50, 39,  8])

In [80]:
arr

array([[31, 50, 39,  8],
       [32, 46, 24, 41],
       [44, 14, 43,  4]])

In [81]:
arr[1,:]

array([32, 46, 24, 41])

In [82]:
arr[: , 2]

array([39, 24, 43])

In [84]:
arr[1:,1:3]

array([[46, 24],
       [14, 43]])

### Broadcasting

In [85]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Boolean indexing

In [87]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr > 6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [89]:
arr[arr > 6]

array([ 7,  8,  9, 10])

In [92]:
arr[arr > 9]

array([10])

In [93]:
arr = np.random.randint(10,50,10)
arr

array([34, 46, 21, 27, 15, 10, 21, 26, 35, 12])

In [97]:
arr[[1,5]]

array([46, 10])

In [100]:
arr[[1,5]]

array([46, 10])

In [101]:
np.max(arr)

46

In [102]:
arr

array([34, 46, 21, 27, 15, 10, 21, 26, 35, 12])

In [103]:
np.min(arr)

10

In [104]:
arr.max()

46

In [105]:
arr = np.arange(1,11)
brr = np.arange(11,21)

In [106]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
brr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [108]:
arr + brr

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])